services:
  app:
    container_name: app
    build:
      context: ./app
    networks:
      appnet:
        ipv4_address: 10.100.11.11
    environment:
      - ORIGIN=http://10.100.11.12:80
    restart: unless-stopped

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      appnet:
        ipv4_address: 10.100.11.12
    restart: unless-stopped

  db:
    container_name: mongodb
    build:
      context: ./db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopasswd
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    networks:
      appnet:
        ipv4_address: 10.100.11.13

networks:
  appnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.11.0/24
#   dbnet:
#     driver: bridge
#     ipam:
#       config:
#         - subnet 10.100.12.0/24
