services:
  app:
    container_name: app
    build:
      context: ./app
    networks:
      appnet:
        ipv4_address: 10.100.11.11
    restart: unless-stopped

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    # volumes:
    #   - /etc/nginx/vhost.d
    #   - /etc/acme.sh
    #   - /usr/share/nginx/html
    #   - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
    networks:
      appnet:
        ipv4_address: 10.100.11.12
    restart: unless-stopped
#   db:
#     image: mongo
#     command:
#     networks:
#       dbnet:
#         ipv4_address: 10.100.12.12
networks:
  appnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.11.0/24
#   dbnet:
#     driver: bridge
#     ipam:
#       config:
#         - subnet 10.100.12.0/24
